### ISSUE TITLE
[Client] Connector should use a caching DNS resolver by default

### ISSUE THREAD

**Issue by kelunik** [reactphp/socket#115]
Doing multiple DNS queries per request might be pretty expensive, depending where the next caching DNS resolver is that the resolver talks to, which might be `8.8.8.8`. Multiple queries, because `A` and `AAAA` usually have to be queries for domains.

**Comment by clue** [comment]
Thanks for filing this ticket, I think you're raising a very good issue here :+1: 

It's a very common setup to connect to the same host over and over again, so I agree that it makes perfect sense to keep a small cache of recent DNS records in memory. However, the default cached resolver does currently not limit the number of cache entries, which is why I've just created https://github.com/reactphp/dns/issues/82 which would need to be implemented first.

(Note that this is not really related to IPv6 addresses (`AAAA` records), I've just created https://github.com/reactphp/socket/issues/116 to keep track of this.)

PRs would be much appreciated! :shipit:
