### ISSUE TITLE
Missing React\Stream\Stream in 0.8.8 version

### ISSUE THREAD

**Issue by mikolajzieba** [reactphp/socket#147]
It looks like there are some wrong dependencies to reactphp/stream package when fetching using composer to install reactphp/socket.

How to reproduce:
`composer require "react/socket" "^0.8.8"`
```
$ cat vendor/react/socket/src/TcpConnector.php| grep "use React\\\\Stream"
use React\Stream\Stream;
```

```
$ cat vendor/react/stream/src/Socket.php
cat: vendor/react/stream/src/Socket.php: No such file or directory
```

When trying to run code with TcpConnector:
```
PHP Warning:  require(xxx/.../React/Stream/Stream.php): failed to open stream: No such file or directory in autoload.php on line 26
```
And it's caused by that line:
vendor/react/dns/src/Query/Executor.php:144

```
        if (!class_exists('React\Stream\Stream')) {
            // prefer DuplexResourceStream as of react/stream v0.7.0
            $conn = new DuplexResourceStream($fd, $this->loop, -1);
        } else {
```

**Comment by clue** [comment]
@mikolajzieba Thank you for reporting this minor oversight! The class import is in fact a leftover and should be removed, but should not cause any issues otherwise. I've just filed #148 to clean up this accordingly :+1: 

The second problem your seeing is more related to your particular autoloader. The code LGTM here, but your autoloader probably shouldn't fail if the code merely checks whether a certain class is available. I would suggest using Compoer's autoloader and this should not be an issue anymore.

If this problem persists, I would suggest filing an issue in react/dns instead and we can discuss this further. Thank you!
