### ISSUE TITLE
Connection write() not send data as separated TCP Packet

### ISSUE THREAD

**Issue by Mindhk92** [reactphp/socket#166]
Hi All,
I have Gate Controller that could be programmed/configured with TCP connection.
I've been trying to send command to the Gate Controller with reactphp/socket.
I've an issue when I try to send multiple command script through tcp connection,
In order for the Gate Controller to read the command, it need to be sent with 1 tcp packet per command.
But with the write() method of the Connection class, all the command got joined as 1 tcp packet eventhough I was sending the command with multiple write()

`
                    foreach($send_data as $sd){
                        $conn->write(hex2bin($sd));
                    }
`

My current workaround is  close the TCP Connection and reopen the TCP Connection for every command I need to send to the GateController. 
But it seems the GateController could not handling many TCP Connection at once,
even after I tried to put timer following after every command.
So the solution is not good.

Is there any method to send data per tcp packet with Connection class without closing the connection, instead of joined all data and send it within 1 tcp packet?

I use Wireshark to monitor the tcp packet.

Regards,
Hendrik

**Comment by clue** [comment]
@Mindhk92 That's an excellent question!

TCP/IP uses the concept of "streams", i.e. it does not know the concept of a "TCP packet". This means that if you write "hello" and "world" to the stream, the receiving side may or may not receive this as individual bytes or bigger chunks.

It sounds like what you're looking for is "message framing". This is a concept where the receiving side has a way to know when a message is completed and the next message begins.

You can use some arbitrary delimiter, such as a newline or NULL character between each message, so that the receiver can know this marks the end of a message. However, this implies it may not be included in the message payload anymore (or you have to escape this). This is commonly used for text based protocols and rarely for protocols transporting binary data.

As an alternative, you can also include the message length in the data. For example, many protocols prepend the message payload with a UINT32 that contains the length of the payload. This way, the receiving side knows how many bytes it needs to read before the next message begins. This is commonly used for binary protocols.

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
