### ISSUE TITLE
Certificate without passphrase must explicitely pass a null passphrase

### ISSUE THREAD

**Issue by jason69** [reactphp/socket#191]
If your local cert has no passphrase, you generally think of:
```php
$server = new React\Socket\Server('tls://127.0.0.1:8000', $loop, array(
    'tls' => array(
        'local_cert' => 'server.pem',
    )
));
```

but it doesn't work: you have to pass a null passphrase:
```php
$server = new React\Socket\Server('tls://127.0.0.1:8000', $loop, array(
    'tls' => array(
        'local_cert' => 'server.pem',
        'passphrase' => null
    )
));
```

This is because of `SecureServer::__construct()`:
```php
// default to empty passphrase to suppress blocking passphrase prompt
$context += array(
    'passphrase' => ''
);
```

I don't really know if "suppress blocking passphrase prompt" is good or bad, but it should at least be documented because you have no errors until you debug and see your server does not sont any certificate (then TLS handshake fails)

**Comment by clue** [comment]
@jason69 Thanks for reporting!

I can not reproduce this locally, perhaps you can help us track this down. This particular line of code is covered by the test suite. If you remove this default assignment and then try to reference an encrypted private key without giving a pasphrase, PHP will start an interactive prompt. Given that this project often runs in non-interactive environments, we figured that assigning a dummy passphrase to report an error is a better alternative.

We're not aware of any issues as you've described in this report. In previous tests, this default assignment was simply ignored if the private key was not encrypted. Can you verify what happens if you remove this default assignment in your environment? Also, what PHP and OpenSSL version are you using? (`php -m` + `php -i | grep -i openssl`)

**Comment by jason69** [comment]
I removed 'passphrase' => null and it still works.

I'm sorry I really don't get it why it still works because i did reproduce it before opening the issue :-(

Anyway, I'm now using a separate certificate and unencrypted key file, and it's working like a charm:
```php
'tls' => [
    'local_cert' => $localCert,
    'local_pk' => $localPk
]
```

Closing this issue right now
