### ISSUE TITLE
how to get a username connections?

### ISSUE THREAD

**Issue by ghasemy50** [reactphp/socket#194]
hi,
i want to see one username has how many connections?
how can i get it separated by username?

**Comment by WyriHaximus** [comment]
Hey this component doesn't have the concept of usernames because it deals with low level TCP connections. The connection object holds some information about the connection but only IP and address for local and remote: https://reactphp.org/socket/#getremoteaddress

You either have to implement that sort of information or use something like Ratchet for websocket connections which already implements certain parts of the protocol you would need to gather that information: https://github.com/ratchetphp/Ratchet

**Comment by ghasemy50** [comment]
how can we sort information?
i'm use leproxy that is based on react.
but i can not limit each user connections.

**Comment by WyriHaximus** [comment]
That's all up to you, tbh I wouldn't even sort it. Also I don't know anything about leproxy's architecture. Maybe this question is better suited there.

**Comment by clue** [comment]
See also https://github.com/leproxy/leproxy/issues/64 for possible duplicate.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
