### ISSUE TITLE
[PHP Bug] Disabling Encryption succeeds silently

### ISSUE THREAD

**Issue by CharlotteDunois** [reactphp/socket#200]
This is the ReactPHP tracking issue for the PHP bug <https://bugs.php.net/bug.php?id=78051> and is related to #199 (<https://github.com/reactphp/socket/pull/199#issuecomment-494116760>).

Bug summary:
```
When you try to disable encryption on a stream socket (with encryption enabled),
the operation succeeds, however PHP reports this as failure.

Both the server and client are able to read and write
successfully after disabling encryption.
```

**Comment by clue** [comment]
@CharlotteDunois Thanks for sharing your finding and letting us know :+1: I agree this is something that we need to be aware of and this is something that should be fixed upstream in PHP itself :+1: 

The way I understand this, this does not currently affect our APIs because we do not support disabling encryption. Additionally, I'm not sure this is even on the roadmap and I would even argue this is rarely used in practice.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can still discuss and/or reopen this :+1:
