### ISSUE TITLE
How can i send new write command to existing connection?

### ISSUE THREAD

**Issue by nemrutco** [reactphp/socket#215]
Hi, I have created a socket server and it works fine when i use telnet to connect and communicate. Now i am trying to build a client using laravel. But i am not sure what to follow or have an idea to implement. I know i can connect to server and send and receive data for the first time but not sure how can i send new commands  to that existing connection when some events happened. 

#### To make it more clear:
- There is a Remote Socket server (Laravel App) (running as daemon)  
- There is a Local Socket Client (Laravel App) (running as daemon)  
- Socket Client did connect to Socket Server using php artisan command and said "hi"
- Socket Server got this message and said "hi back"

Until here every thing is fine. My issue starts when:

Let's say sometime in future one of the API request needs to send a request to Socket server and get response from it. How can i reference the existing connection from API controller to send it a write command ?
For now i am brainstorming as: 
```php
<?php
namespace App\Services;
use React\Socket\Connector;
use React\EventLoop\Factory;
use React\Socket\ConnectionInterface;
class SocketClient
{
    public $client;
    public function __construct()
    {
        $loop =  Factory::create();
        $connector = new Connector($loop);
        $connector->connect(env('SOCKET_SERVER', '127.0.0.1:9000'))
            ->then(function (ConnectionInterface $connection) {
                $this->client = $connection;
            }, function (Exception $e) {
                $this->client = $e->getMessage();
            });
        $loop->run();
    }
}
```

Thanks

**Comment by nemrutco** [comment]
brainstorming v2: 
Let's imagine our `Socket Server` has a `Pool` and all the new connections are added to the pool by a `unique id`. Let's say every client connection request has an `api token` so we can save it to the pool when we add them. So now we can map each connected clients from the pool. 

Since i am not so sure how can i reference the existing connection to the server, instead i can create a `Temporary Client` which holds a `trigger command` and `same api token` which will response to existing client. And existing client will` trigger the event` depends on what has been requested. To make it more clear:

- `Socket Server` starts. Let's call this `Socket Server`
- `Socket Client` connects with an api token. Let's call this one `Socket Client`
- `Socket Server` adds `Socket Cient` with `api token` key map to the `SplObjectStorage`  pool
- `Connection established` and waiting for events
- From same `Socket Client` application, a new `Temporary Client` connection starts with the same api token. Let's call this one `Temporary Client`
- `Temporary Client` will make a new request and close the connection once request has been made. 
- `Socket Server` will send the response to `Socket Client` since `Socket Server` will check the api token and map the `Socket Client` to send back the response. 
- Do this loop for each new request

I have tried and it kind of works but i believe this is totally wrong way. Shouldn't be this complicated :) Since i can't find an answer, currently struggling around..

**Comment by WyriHaximus** [comment]
> I have tried and it kind of works but i believe this is totally wrong way. Shouldn't be this complicated :) Since i can't find an answer, currently struggling around..

Can you gist a slimmed down version of this, without the business logic here?: https://gist.github.com/

Feels like I'm missing some context. You've mentioned API controllers, are those controllers handling HTTP calls from fpm or react/http?

**Comment by nemrutco** [comment]
I could write gigs but it's a bit complicated without some business logic. Let me know if this helps:
API Requests are first Handled by Laravel and forwarded by Reactphp.

- The main request enters to Laravel application via API request. 
- Laravel application uses Reactphp Client to forward this request to remote via Socket client, and Remote server which is runing React Socket server handles the request and forwards it to the its Laravel API. 
- API does its job and give the response to the Socket server to response all the way back.

**Comment by nemrutco** [comment]
> Feels like I'm missing some context. You've mentioned API controllers, are those controllers handling HTTP calls from fpm or react/http?

here is the gist
https://gist.github.com/nemrutco/84355599ab6798bcc3019ce091672e00

**Comment by clue** [comment]
@nemrutco Thanks for the detailed description and the gist. I'm not sure I follow exactly what you're trying to achieve, but form the details you've posted it seems like you might be overthinking the problem.

Here's how I understand your problem: Your web application (Laravel) handles an incoming HTTP request, forwards some JSON data to a ReactPHP-based server and should wait for its response data?

In this case, your problem can be split into two independent problems:
* Your traditional application has to "talk" to your ReactPHP server, send data and wait to receive a response
* Your ReactPHP application needs to accept this data and send back a response.

This means you have to find a communication protocol between both parts that allow this communication. Unless you have more specific requirements, I would highly suggest sticking to HTTP because there are existing implementations for pretty much any situation, including existing HTTP client for your traditional application and an HTTP server for ReactPHP.

If you want to get started with HTTP communication, I would suggest taking a look at https://github.com/reactphp/http which includes examples for common scenarios and more complex ones such as streaming.

I'm mentioning this because your application seems to implement some kind of streaming mechanism where the connection from your client to your application is meant to be kept open for a longer period of time? In this case, a traditional framework like Laravel is probably a bad fit, because it builds on top of PHP's request-response semantics. You may want to use ReactPHP's HTTP server component linked about to build a streaming server and/or using WebSockets (https://github.com/beyondcode/laravel-websockets).

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can still discuss and/or reopen this :+1:
