### ISSUE TITLE
Why is `$loop` private?

### ISSUE THREAD

**Issue by SamMousa** [reactphp/socket#40]
When creating a subclass of the socket server I am forced to override the constructor if I want to access the loop. What is the argument for making `$loop` private instead of protected?

**Comment by staabm** [comment]
because encapsulation.

**Comment by SamMousa** [comment]
So making `$loop` protected is breaking encapsulation too much, but having a public `$master` doesn't??

What is the practical downside of making a dependency that might be used by subclasses available to them? 
Alternatively it could at least be made available via a getter.

**Comment by staabm** [comment]
just capture it with `__construct` ... a lot easier then meaningless getters or anything.

**Comment by SamMousa** [comment]
@staabm I know I can capture it and that's what I do now, I'd just rather not have to.
The goal of this ticket is not to solve my problem, but to possibly improve the library.

Anyway, feel free to close if you feel this would not be an improvement.

**Comment by clue** [comment]
The `$loop` is private because we don't want this to become part of our public API. Keeping this private allows us to change these implementation details without introducing BC breaks.

I agree that keeping this as-is encourages a cleaner design because it makes `extend`ing the server more difficult and encourages composition (DI) instead.

This has also already been covered in #12, #14 and #27.

I hope this helps :+1: I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we may reopen this :+1:
